DFXswiss/wallet

shared/api/dfx/ApiService.ts, shared/api/dfx/models/ApiDto.ts, shared/contexts/DFXAPIContextProvider.tsx
- added QueryParam logic to API Layer
- change default signingMessage to fetched message variant (fallback => old hardcoded version)
/kind feature
/kind refactor
=> DEV-646 sign message

mobile-app/app/hooks/useShowAdvertisement.ts, mobile-app/app/screens/RootNavigator.tsx
- reactivate ads
- fix clear interval
/kind fix
=> DEV-637 reactivate ads

mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts
=> dev-797 show return stabilisation info

shared/translations/languages/fr.json
=> Korrektur Übersetzung

mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockStakingCard.tsx, shared/api/dfx/ApiService.ts, shared/store/wallet.ts
=> [DEV-1305] lock dfi ym

.github/workflows/app-dev.yml, .github/workflows/app-prd.yml, .github/workflows/app-pre.yml
=> [NO-TASK] added workflows for preview & production channels

mobile-app/app/components/LOCK/RewardStrategy.tsx, mobile-app/app/components/LOCK/modals/RewardStrategyInfo.tsx, mobile-app/app/contexts/LOCK/LockContextProvider.tsx, mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockStakingCard.tsx, shared/api/dfx/ApiService.ts
=> [DEV-1131] first set of fixes

mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/components/LOCK/RewardStrategy.tsx, mobile-app/app/components/LOCK/modals/RewardFilterSelection.tsx
=> [DEV-1131] changed payout asset selection sheet

mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/components/BottomSheetWithNav.tsx, mobile-app/app/components/IconButton.tsx, mobile-app/app/components/LOCK/AddressInput.tsx, mobile-app/app/components/LOCK/ListItem.tsx, mobile-app/app/components/LOCK/RewardPercent.tsx, mobile-app/app/components/LOCK/RewardStrategy.tsx, mobile-app/app/components/LOCK/StakingCard.tsx, mobile-app/app/components/LOCK/modals/RewardDestinationAddress.tsx, mobile-app/app/components/LOCK/modals/RewardDestinationSelection.tsx, mobile-app/app/components/LOCK/modals/RewardFilterSelection.tsx, mobile-app/app/components/LOCK/modals/RewardStrategyInfo.tsx, mobile-app/app/components/themed/ThemedTouchableOpacity.tsx, mobile-app/app/constants/LOCK/RewardRouteDestination.ts, mobile-app/app/constants/LOCK/RewardStrategyType.ts, mobile-app/app/constants/LOCK/StakingAction.ts, mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx, mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, mobile-app/app/screens/RootNavigator.tsx, shared/api/dfx/ApiService.ts, shared/environment.ts
=> [DEV-1131] reward div

mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/components/BottomSheetWithNav.tsx, mobile-app/app/components/IconButton.tsx, mobile-app/app/components/LOCK/AddressInput.tsx, mobile-app/app/components/LOCK/ListItem.tsx, mobile-app/app/components/LOCK/RewardPercent.tsx, mobile-app/app/components/LOCK/RewardStrategy.tsx, mobile-app/app/components/LOCK/StakingCard.tsx, mobile-app/app/components/LOCK/modals/RewardDestinationAddress.tsx, mobile-app/app/components/LOCK/modals/RewardDestinationSelection.tsx, mobile-app/app/components/LOCK/modals/RewardFilterSelection.tsx, mobile-app/app/components/LOCK/modals/RewardStrategyInfo.tsx, mobile-app/app/components/themed/ThemedTouchableOpacity.tsx, mobile-app/app/constants/LOCK/RewardRouteDestination.ts, mobile-app/app/constants/LOCK/RewardStrategyType.ts, mobile-app/app/constants/LOCK/StakingAction.ts, mobile-app/app/contexts/LOCK/LockContextProvider.tsx, mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx, mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockStakingCard.tsx, mobile-app/app/screens/RootNavigator.tsx, shared/api/dfx/ApiService.ts, shared/environment.ts
=> [PREVIEW] Reward diversification v1

mobile-app/app/components/LOCK/AddressInput.tsx, mobile-app/app/components/LOCK/ListItem.tsx, mobile-app/app/components/LOCK/RewardPercent.tsx, mobile-app/app/components/LOCK/modals/RewardDestinationAddress.tsx, mobile-app/app/components/WalletTextInput.tsx
=> [DEV-1131] rew div fixes

mobile-app/app/components/LOCK/RewardStrategy.tsx
=> [DEV-1131] fixes floating display error

.github/workflows/app-dev.yml, .github/workflows/app-prd.yml, .github/workflows/app-pre.yml, mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/components/DfxKycInfo.tsx, mobile-app/app/components/InputHelperText.tsx, mobile-app/app/components/LOCK/AmountRow.tsx, mobile-app/app/components/LOCK/BottomSheetStaking.tsx, mobile-app/app/components/LOCK/ListItem.tsx, mobile-app/app/components/LOCK/StakingCard.tsx, mobile-app/app/components/WalletTextInput.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, shared/api/dfx/ApiService.ts
=> [DEV-1340] new ym tokens

.github/workflows/app-dev.yml, .github/workflows/app-prd.yml, .github/workflows/app-pre.yml, mobile-app/app/components/BottomSheetTokenList.tsx, mobile-app/app/components/DfxKycInfo.tsx, mobile-app/app/components/InputHelperText.tsx, mobile-app/app/components/LOCK/AmountRow.tsx, mobile-app/app/components/LOCK/BottomSheetStaking.tsx, mobile-app/app/components/LOCK/ListItem.tsx, mobile-app/app/components/LOCK/StakingCard.tsx, mobile-app/app/components/WalletTextInput.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx, shared/api/dfx/ApiService.ts
* [DEV-1340] fixes issues regarding mapping for other ym-balances
* [DEV-1340] fixed min deposit for ym deposits and removed capping
* [DEV-1340] added min deposit label
* [NO-TASK] lowered kyc max amount to 990
* [DEV-1340] CRC and other fixing due to first testing
* [DEV-1340] CRC
* [DEV-1340] fixes broken token list
* [DEV-1340] changing ym balances to 4 decimals
/kind
Fixes #
[DEV-1340]: https://dfxswiss.atlassian.net/browse/DEV-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1340]: https://dfxswiss.atlassian.net/browse/DEV-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1340]: https://dfxswiss.atlassian.net/browse/DEV-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> [DEV-1340] new ym tokens (#54)

mobile-app/app/components/LOCK/StakingCard.tsx, mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx
=> [DEV-1340] fixes reinvest YM availability

mobile-app/app/components/LOCK/BottomSheetStaking.tsx, mobile-app/app/constants/LOCK/TransactionCache.ts, mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx
=> [DEV-1353] fixes issue with wrong deposits and cache invalidation

mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Settings/screens/BackupExplanation.tsx
=> [DEV-1389] fixes title for bottom sheet

mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx, mobile-app/app/screens/AppNavigator/screens/Loans/hooks/CollateralPrice.ts, mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx, mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelines.tsx, shared/translations/languages/de.json
=> [NO-TASK] updated to correct TnC urls

mobile-app/app/api/persistence/dfx_storage.ts, mobile-app/app/screens/AppNavigator/screens/Portfolio/components/DfxButtons.tsx, mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelines.tsx
=> [DEV-1389] fixed issue of displaying backup not verified for all users

mobile-app/app/components/InfoText.tsx, mobile-app/app/components/InputHelperText.tsx, mobile-app/app/components/LOCK/AmountRow.tsx, mobile-app/app/components/LOCK/BottomSheetStaking.tsx, mobile-app/app/components/WalletTextInput.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx
=> [DEV-1091] improved staking and deposit for LOCK

mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockStakingCard.tsx, shared/contexts/DFXAPIContextProvider.tsx
=> [NO-TASK] fixes issue with not allowed for sign ups

mobile-app/app/components/LOCK/BottomSheetStaking.tsx
=> [DEV-1091] fixes issue with wrong asset in description

mobile-app/app/components/LOCK/BottomSheetStaking.tsx
=> [DEV-1091] fixes utxo hint label from going offscreen

mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/components/DFIBalanceCard.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenBreakdownDetails.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx, shared/api/dfx/ApiService.ts
=> [DEV-1000] added LOCK deposited balance

mobile-app/app/components/LOCK/modals/PendingRewardInfo.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockTransactions.tsx
=> [DEV-1425] adapted to new wording

mobile-app/app/contexts/LOCK/LockStakingContextProvider.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx
=> Fixes wrong value on deposited @ LOCK

mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx
=> [NO-TASK] change to compact

mobile-app/app/screens/AppNavigator/screens/Portfolio/LOCK/LockDashboardScreen.tsx
=> Change LOCK CSV export to compact

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioNavigator.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/BuyConfirmationScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/BuyScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ReceiveDTokenScreen.tsx, mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SellScreen.tsx, shared/api/dfx/models/BuyRoute.ts, shared/api/dfx/models/CryptoRoute.ts, shared/api/dfx/models/SellRoute.ts
=> [DEV-1480] adapted to new min deposit changes for buy & btc deposit
